"""empty message

Revision ID: 9a21deb64749
Revises: a71d75b0dac7
Create Date: 2020-02-17 14:36:13.536211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a21deb64749'
down_revision = 'a71d75b0dac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.String(length=120), nullable=False))
    op.drop_column('Shows', 'genres')
    op.drop_column('Shows', 'phone')
    op.drop_column('Shows', 'facebook_link')
    op.drop_column('Shows', 'city')
    op.drop_column('Shows', 'state')
    op.drop_column('Shows', 'image_link')
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.add_column('Shows', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
